sudo: required
language: java
jdk:
- oraclejdk8
script: mvn clean install
install: true
notifications:
  email:
    recipients:
    - ybrin.development@gmail.com
    - simon.artner@gmail.com
    on_success: change
    on_failure: always
  webhooks: https://api.kwstudios.org/travis/webhooks/versions
before_install:
- ./run_buildtools.sh
# Cache maven directory for faster builds
cache:
  directories:
  - $HOME/.m2
before_deploy:
- ls
- cd target/
- ls
- cd ..
deploy:
  - provider: releases
    api_key:
      secure: MXvyvKNlEOhNV7um+lY1Np3aGmZlNvMXCsrRZBKkLs7EiSiinRWt5S4jjYwbXu/P+$
    file_glob: true
    file: ${HOME}/build/${TRAVIS_REPO_SLUG}/target/ragemode*.jar
    skip_cleanup: true
    on:
      repo: KWStudios/RageMode
      tags: true
  - provider: gcs
    access_key_id: GOOGOORZ55TL3TFGHJHZ
    secret_access_key:
      secure: lmfQjmHqzZmwSG4JvSCcFCVUZfh1JLiVlsqBTk0OhnUSfAhxp68lfL+X178vjPeJoCHe0B/P+q3d5+JlBgru9ZjnIPhr+QSZF1j+QnPTssoPooVALAw2behhACi6s5cLDipbjeqIBMYzuEFanBHGNU+fjEpNhlvgKBUGXoGxaiqGSKcY3Jm5y0c/e1ij2Fmspio8uQkPlhYf9dflZkCN9AiAxg64jJi4LBJCAgZ3kmlc+MnXa7TAJsyLwX6SwEpMjRjVWeMqGg2H6LYVV7rTFVU3FFMbQCq0U8kjQQF009dMkfY6L9ZrDq7YZy2vAb2glOHtDYwaQid3iCAVGM6BbPaqRdq9xqQ1mwD6EoXbtWHKrc9uYyqII0LdLR7CWXqPDMPRnh8DRDG0Fzq1Nxwc0qON6Zat9iME16W7nl3elH4ep0Px7mH0djIVfCDPZjUild9bxZfK5pVFEZ40FkknGIl1N2kZKSB7DuPE1EHG63Pap0rRxorZq+r89YYVlY13XV6yAWP4b9qfX8oTVqDrBuHvwOu6iGZcWjbOHyTDfTt7u1xjj4nkUM9IR5lUmwb4C2wj5QfC8YUvMW0Jk6A2iHK1bhTJ5JK5oxbD6c4XrvDMrlFf6QGjiTpjS/as8MrPSOYd/n+n4URiaXBNMqyf4FZK6yaExuje/eyLeJjbNh8=
    file_glob: true
    bucket: kwstudios-main-bucket
    local-dir: "${HOME}/build/${TRAVIS_REPO_SLUG}/target"
    upload-dir: travis/ragemode/${TRAVIS_BUILD_NUMBER}
    skip_cleanup: true
    acl: public-read
    on:
      repo: KWStudios/RageMode
